name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

env:
  CACHE_NUMBER: 0  # bump this to invalidate cache manually

jobs:
  build_test:
    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests with pytest
        run: pytest --cov --cov-report=xml

      # Only upload coverage once (not from every OS/Python combo)
      - name: Upload Coverage to Codacy
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
        uses: codacy/codacy-coverage-reporter-action@v1.3
        with:
          coverage-reports: ./coverage.xml
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
